stages:
  generate_new_data:
    cmd: python src/generate_new_data.py
    deps:
      - src/generate_new_data.py
      - params.yaml
      - train/train.csv
    outs:
      - data/new_data.csv

  preprocess:
    cmd: python src/preprocess_new_data.py
    deps:
      - src/preprocess_new_data.py
      - params.yaml
      - train/train.csv
      - data/new_data.csv
    outs:
      - artifacts/processed_train.csv

  monitor:
    cmd: python src/monitor.py
    deps:
      - src/monitor.py
      - params.yaml
      - train/train.csv
      - data/new_data.csv
    outs:
      - monitoring/reports/drift_report.json:
          cache: false
      - monitoring/alerts/alerts.json:
          cache: false
      - monitoring/logs/monitoring.log:
          cache: false

  train:
    cmd: python src/model.py
    deps:
      - src/model.py
      - params.yaml
      - artifacts/processed_train.csv
      - monitoring/reports/drift_report.json
    outs:
      - models/best_model.joblib

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - params.yaml
      - test/test.csv
      - models/best_model.joblib
    metrics:
      - metrics.json:
          cache: false
    outs:
      - metrics.txt:
          cache: false
      - model_results.png:
          cache: false
      - artifacts/model_results.png:
          cache: false